# Generated by Django 4.1 on 2024-03-16 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfolder',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_craft_back.character'),
        ),
    ]
