# Generated by Django 4.1 on 2024-05-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0004_relationshiptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.CharField(max_length=255)),
                ('to_node', models.CharField(max_length=255)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w_craft_back.relationshiptype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w_craft_back.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w_craft_back.userkey')),
            ],
        ),
    ]
