# Generated manually for Character Studio MVP.

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("w_craft_back", "0005_graphedge"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioCharacter",
            fields=[
                ("character_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, default="", max_length=100)),
                ("short_description", models.TextField(blank=True, default="")),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, default="", max_length=100)),
                ("species", models.CharField(default="human", max_length=100)),
                ("visual_style", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("approved", "Approved"),
                            ("identity_locked", "Identity locked"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("identity_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("personality", models.JSONField(blank=True, default=dict)),
                ("speech_style", models.TextField(blank=True, default="")),
                ("backstory", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="locked_studio_characters", to="w_craft_back.userkey")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="studio_characters", to="w_craft_back.project")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="studio_characters", to="w_craft_back.userkey")),
            ],
            options={
                "db_table": "characters",
            },
        ),
        migrations.CreateModel(
            name="CharacterAppearance",
            fields=[
                ("appearance_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("face_shape", models.CharField(blank=True, default="", max_length=100)),
                ("skin_tone", models.CharField(blank=True, default="", max_length=100)),
                ("eye_shape", models.CharField(blank=True, default="", max_length=100)),
                ("eye_color", models.CharField(blank=True, default="", max_length=100)),
                ("eyebrow_shape", models.CharField(blank=True, default="", max_length=100)),
                ("nose_shape", models.CharField(blank=True, default="", max_length=100)),
                ("lips_shape", models.CharField(blank=True, default="", max_length=100)),
                ("jawline", models.CharField(blank=True, default="", max_length=100)),
                ("hair_length", models.CharField(blank=True, default="", max_length=100)),
                ("hair_style", models.CharField(blank=True, default="", max_length=100)),
                ("hair_color", models.CharField(blank=True, default="", max_length=100)),
                ("hair_details", models.JSONField(blank=True, default=dict)),
                ("height", models.CharField(blank=True, default="", max_length=100)),
                ("body_type", models.CharField(blank=True, default="", max_length=100)),
                ("posture", models.CharField(blank=True, default="", max_length=100)),
                ("distinctive_features", models.JSONField(blank=True, default=list)),
                ("appearance_prompt", models.TextField(blank=True, default="")),
                ("negative_prompt", models.TextField(blank=True, default="")),
                ("source_type", models.CharField(blank=True, default="", max_length=100)),
                ("source_description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appearances", to="w_craft_back.studiocharacter")),
            ],
            options={
                "db_table": "character_appearances",
            },
        ),
        migrations.CreateModel(
            name="CharacterAsset",
            fields=[
                ("asset_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("uploaded_reference", "Uploaded reference"),
                            ("initial_variant", "Initial variant"),
                            ("edit_variant", "Edit variant"),
                            ("canonical_reference", "Canonical reference"),
                            ("portrait", "Portrait"),
                            ("full_body", "Full body"),
                            ("face_closeup", "Face closeup"),
                            ("front_view", "Front view"),
                            ("side_view", "Side view"),
                            ("expression", "Expression"),
                            ("outfit_reference", "Outfit reference"),
                            ("thumbnail", "Thumbnail"),
                        ],
                        max_length=64,
                    ),
                ),
                ("image_url", models.TextField(blank=True, default="")),
                ("storage_path", models.TextField(blank=True, default="")),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_canonical", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                ("source_job_id", models.UUIDField(blank=True, null=True)),
                ("source_variant_id", models.UUIDField(blank=True, null=True)),
                ("generation_prompt", models.TextField(blank=True, default="")),
                ("negative_prompt", models.TextField(blank=True, default="")),
                ("model_name", models.CharField(blank=True, default="", max_length=100)),
                ("model_version", models.CharField(blank=True, default="", max_length=100)),
                ("seed", models.BigIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("safety_status", models.CharField(blank=True, default="unchecked", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assets", to="w_craft_back.studiocharacter")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="character_assets", to="w_craft_back.project")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="character_assets", to="w_craft_back.userkey")),
            ],
            options={
                "db_table": "character_assets",
            },
        ),
        migrations.CreateModel(
            name="CharacterOutfit",
            fields=[
                ("outfit_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("style", models.CharField(blank=True, default="", max_length=100)),
                ("color_palette", models.JSONField(blank=True, default=list)),
                ("layers", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outfits", to="w_craft_back.studiocharacter")),
                ("reference_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="outfit_references", to="w_craft_back.characterasset")),
            ],
            options={
                "db_table": "character_outfits",
            },
        ),
        migrations.CreateModel(
            name="CharacterVersion",
            fields=[
                ("version_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appearance", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="w_craft_back.characterappearance")),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="w_craft_back.studiocharacter")),
                ("outfit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="w_craft_back.characteroutfit")),
                ("reference_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="w_craft_back.characterasset")),
            ],
            options={
                "db_table": "character_versions",
            },
        ),
        migrations.CreateModel(
            name="CharacterGenerationJob",
            fields=[
                ("job_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("job_type", models.CharField(choices=[("initial_variants", "Initial variants"), ("edit_variants", "Edit variants"), ("outfit_variants", "Outfit variants"), ("expression_variants", "Expression variants"), ("character_sheet", "Character sheet"), ("reference_extraction", "Reference extraction")], max_length=64)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=32)),
                ("region", models.CharField(choices=[("face", "Face"), ("hair", "Hair"), ("body", "Body"), ("outfit", "Outfit"), ("style", "Style"), ("full_character", "Full character")], default="full_character", max_length=32)),
                ("variant_count", models.PositiveSmallIntegerField(default=4)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("compiled_prompt", models.TextField(blank=True, default="")),
                ("negative_prompt", models.TextField(blank=True, default="")),
                ("edit_instruction", models.TextField(blank=True, default="")),
                ("preserve_options", models.JSONField(blank=True, default=dict)),
                ("provider", models.CharField(blank=True, default="mock", max_length=100)),
                ("model_name", models.CharField(blank=True, default="", max_length=100)),
                ("model_version", models.CharField(blank=True, default="", max_length=100)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_code", models.CharField(blank=True, default="", max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="generation_jobs", to="w_craft_back.studiocharacter")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="character_generation_jobs", to="w_craft_back.project")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="character_generation_jobs", to="w_craft_back.userkey")),
            ],
            options={
                "db_table": "character_generation_jobs",
            },
        ),
        migrations.CreateModel(
            name="CharacterVariant",
            fields=[
                ("variant_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("variant_index", models.PositiveSmallIntegerField()),
                ("region", models.CharField(choices=[("face", "Face"), ("hair", "Hair"), ("body", "Body"), ("outfit", "Outfit"), ("style", "Style"), ("full_character", "Full character")], max_length=32)),
                ("controls_snapshot", models.JSONField(blank=True, default=dict)),
                ("appearance_snapshot", models.JSONField(blank=True, default=dict)),
                ("image_url", models.TextField(blank=True, default="")),
                ("prompt", models.TextField(blank=True, default="")),
                ("negative_prompt", models.TextField(blank=True, default="")),
                ("seed", models.BigIntegerField(blank=True, null=True)),
                ("model_name", models.CharField(blank=True, default="", max_length=100)),
                ("status", models.CharField(choices=[("generated", "Generated"), ("applied", "Applied"), ("discarded", "Discarded")], default="generated", max_length=32)),
                ("applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="variants", to="w_craft_back.characterasset")),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="w_craft_back.studiocharacter")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="w_craft_back.charactergenerationjob")),
            ],
            options={
                "db_table": "character_variants",
            },
        ),
        migrations.CreateModel(
            name="CharacterRevision",
            fields=[
                ("revision_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("revision_number", models.PositiveIntegerField()),
                ("change_type", models.CharField(choices=[("initial_create", "Initial create"), ("apply_variant", "Apply variant"), ("manual_update", "Manual update"), ("outfit_change", "Outfit change"), ("identity_lock", "Identity lock"), ("restore_revision", "Restore revision"), ("version_create", "Version create")], max_length=64)),
                ("changed_region", models.CharField(blank=True, choices=[("face", "Face"), ("hair", "Hair"), ("body", "Body"), ("outfit", "Outfit"), ("style", "Style"), ("full_character", "Full character")], default="", max_length=32)),
                ("change_summary", models.TextField(blank=True, default="")),
                ("text_refinement", models.TextField(blank=True, default="")),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("appearance", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="w_craft_back.characterappearance")),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="w_craft_back.studiocharacter")),
                ("outfit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="w_craft_back.characteroutfit")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="character_revisions", to="w_craft_back.project")),
                ("reference_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="w_craft_back.characterasset")),
                ("source_job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="w_craft_back.charactergenerationjob")),
                ("source_variant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="w_craft_back.charactervariant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="character_revisions", to="w_craft_back.userkey")),
                ("version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="w_craft_back.characterversion")),
            ],
            options={
                "db_table": "character_revisions",
            },
        ),
        migrations.CreateModel(
            name="CharacterExpression",
            fields=[
                ("expression_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("expression_type", models.CharField(choices=[("neutral", "Neutral"), ("happy", "Happy"), ("sad", "Sad"), ("angry", "Angry"), ("scared", "Scared"), ("surprised", "Surprised"), ("tired", "Tired"), ("sarcastic", "Sarcastic"), ("confused", "Confused"), ("crying", "Crying"), ("smirking", "Smirking")], max_length=32)),
                ("description", models.TextField(blank=True, default="")),
                ("prompt", models.TextField(blank=True, default="")),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="w_craft_back.characterasset")),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expressions", to="w_craft_back.studiocharacter")),
            ],
            options={
                "db_table": "character_expressions",
            },
        ),
        migrations.CreateModel(
            name="CharacterRelationship",
            fields=[
                ("relationship_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("relation_type", models.CharField(max_length=100)),
                ("dynamic_description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="character_relationships", to="w_craft_back.project")),
                ("source_character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_relationships", to="w_craft_back.studiocharacter")),
                ("target_character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="incoming_relationships", to="w_craft_back.studiocharacter")),
            ],
            options={
                "db_table": "character_relationships",
            },
        ),
        migrations.AddField(model_name="studiocharacter", name="active_appearance", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="w_craft_back.characterappearance")),
        migrations.AddField(model_name="studiocharacter", name="active_outfit", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="w_craft_back.characteroutfit")),
        migrations.AddField(model_name="studiocharacter", name="active_version", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="w_craft_back.characterversion")),
        migrations.AddField(model_name="studiocharacter", name="canonical_reference_image", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="canonical_for_characters", to="w_craft_back.characterasset")),
        migrations.AddField(model_name="studiocharacter", name="current_revision", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="w_craft_back.characterrevision")),
        migrations.AddIndex(model_name="studiocharacter", index=models.Index(fields=["project"], name="characters_project_95fdda_idx")),
        migrations.AddIndex(model_name="studiocharacter", index=models.Index(fields=["user"], name="characters_user_id_6db2fe_idx")),
        migrations.AddIndex(model_name="studiocharacter", index=models.Index(fields=["status"], name="characters_status_49cf2d_idx")),
        migrations.AddIndex(model_name="studiocharacter", index=models.Index(fields=["project", "status"], name="characters_project_cac846_idx")),
        migrations.AddIndex(model_name="characterappearance", index=models.Index(fields=["character"], name="character_a_charact_7741ba_idx")),
        migrations.AddIndex(model_name="characteroutfit", index=models.Index(fields=["character"], name="character_o_charact_a255ad_idx")),
        migrations.AddIndex(model_name="characterversion", index=models.Index(fields=["character"], name="character_v_charact_4f112f_idx")),
        migrations.AddIndex(model_name="characterasset", index=models.Index(fields=["character"], name="character_a_charact_0d1067_idx")),
        migrations.AddIndex(model_name="characterasset", index=models.Index(fields=["project"], name="character_a_project_d415f6_idx")),
        migrations.AddIndex(model_name="characterasset", index=models.Index(fields=["asset_type"], name="character_a_asset_t_07aa97_idx")),
        migrations.AddIndex(model_name="charactergenerationjob", index=models.Index(fields=["character"], name="character_g_charact_18486e_idx")),
        migrations.AddIndex(model_name="charactergenerationjob", index=models.Index(fields=["project"], name="character_g_project_a65b63_idx")),
        migrations.AddIndex(model_name="charactergenerationjob", index=models.Index(fields=["status"], name="character_g_status_a1b6e0_idx")),
        migrations.AddIndex(model_name="charactervariant", index=models.Index(fields=["job"], name="character_v_job_id_e5472d_idx")),
        migrations.AddIndex(model_name="charactervariant", index=models.Index(fields=["character"], name="character_v_charact_e045f1_idx")),
        migrations.AddIndex(model_name="characterrevision", index=models.Index(fields=["character"], name="character_r_charact_222f6e_idx")),
        migrations.AddConstraint(model_name="characterrevision", constraint=models.UniqueConstraint(fields=("character", "revision_number"), name="uniq_character_revision_number")),
        migrations.AddIndex(model_name="characterexpression", index=models.Index(fields=["character"], name="character_e_charact_44bd33_idx")),
        migrations.AddIndex(model_name="characterrelationship", index=models.Index(fields=["project"], name="character_r_project_9c31c7_idx")),
        migrations.AddIndex(model_name="characterrelationship", index=models.Index(fields=["source_character"], name="character_r_source__a745ef_idx")),
        migrations.AddIndex(model_name="characterrelationship", index=models.Index(fields=["target_character"], name="character_r_target__097a76_idx")),
    ]

