# Generated by Django 4.1 on 2026-04-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0012_relax_generation_variant_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studiocharacter',
            name='characters_status_49cf2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='studiocharacter',
            name='characters_project_cac846_idx',
        ),
        migrations.RemoveField(
            model_name='studiocharacter',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='studiocharacter',
            name='status',
        ),
    ]
