# Generated by Django 5.2.13 on 2026-05-09 06:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0022_subscriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('is_created', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='projects/music/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/music/covers/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('character_created', 'Персонаж создан'), ('character_updated', 'Персонаж обновлён'), ('scene_created', 'Сцена создана'), ('scene_render_completed', 'Рендер сцены завершён'), ('music_added', 'Музыка добавлена'), ('location_created', 'Локация создана'), ('asset_uploaded', 'Файл загружен'), ('project_updated', 'Проект обновлён')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/assets/')),
                ('asset_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ'), ('reference', 'Референс'), ('storyboard', 'Сториборд'), ('model_3d', '3D модель')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGenerationJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('character_image', 'Генерация персонажа'), ('scene_image', 'Генерация сцены'), ('reference_sheet', 'Референсы персонажа'), ('video', 'Генерация видео'), ('music', 'Генерация музыки'), ('location', 'Генерация локации')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='queued', max_length=20)),
                ('prompt', models.TextField(blank=True, default='')),
                ('negative_prompt', models.TextField(blank=True, default='')),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('editor', 'Редактор'), ('viewer', 'Просмотр')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('script_progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('visual_progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('audio_progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('postproduction_progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('script_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('script_ready', 'Сценарий готов'), ('storyboard_ready', 'Сториборд готов'), ('rendering', 'Рендерится'), ('completed', 'Завершена'), ('failed', 'Ошибка')], default='draft', max_length=20)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='scenes/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SceneCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_scene', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SceneMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_seconds', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/covers/'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('completed', 'Завершён'), ('archived', 'В архиве')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'status'], name='w_craft_bac_owner_i_42db0d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'updated_at'], name='w_craft_bac_owner_i_f79d14_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='w_craft_bac_status_c4bd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='w_craft_bac_slug_8fdee7_idx'),
        ),
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='w_craft_back.project'),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to='w_craft_back.project'),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='w_craft_back.project'),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectasset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='w_craft_back.project'),
        ),
        migrations.AddField(
            model_name='projectasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgenerationjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='w_craft_back.project'),
        ),
        migrations.AddField(
            model_name='projectgenerationjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_generation_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='w_craft_back.project'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='w_craft_back.project'),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='w_craft_back.project'),
        ),
        migrations.AddField(
            model_name='scene',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='w_craft_back.location'),
        ),
        migrations.AddField(
            model_name='scene',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='w_craft_back.project'),
        ),
        migrations.AddField(
            model_name='scenecharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_appearances', to='w_craft_back.studiocharacter'),
        ),
        migrations.AddField(
            model_name='scenecharacter',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_characters', to='w_craft_back.scene'),
        ),
        migrations.AddField(
            model_name='scenemusic',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_music', to='w_craft_back.scene'),
        ),
        migrations.AddField(
            model_name='scenemusic',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_usages', to='w_craft_back.musictrack'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['project'], name='w_craft_bac_project_420d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['project', 'is_created'], name='w_craft_bac_project_556c41_idx'),
        ),
        migrations.AddIndex(
            model_name='musictrack',
            index=models.Index(fields=['project'], name='w_craft_bac_project_5eb4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='musictrack',
            index=models.Index(fields=['project', 'updated_at'], name='w_craft_bac_project_532b89_idx'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['project', 'created_at'], name='w_craft_bac_project_04d419_idx'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['activity_type'], name='w_craft_bac_activit_180c62_idx'),
        ),
        migrations.AddIndex(
            model_name='projectasset',
            index=models.Index(fields=['project', 'asset_type'], name='w_craft_bac_project_dc42ea_idx'),
        ),
        migrations.AddIndex(
            model_name='projectasset',
            index=models.Index(fields=['project', 'created_at'], name='w_craft_bac_project_91a385_idx'),
        ),
        migrations.AddIndex(
            model_name='projectasset',
            index=models.Index(fields=['uploaded_by'], name='w_craft_bac_uploade_639495_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgenerationjob',
            index=models.Index(fields=['project', 'status'], name='w_craft_bac_project_fb1d79_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgenerationjob',
            index=models.Index(fields=['user', 'status'], name='w_craft_bac_user_id_b358bc_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgenerationjob',
            index=models.Index(fields=['job_type', 'status'], name='w_craft_bac_job_typ_ac8a35_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgenerationjob',
            index=models.Index(fields=['created_at'], name='w_craft_bac_created_1af81c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'role'], name='w_craft_bac_project_1f45a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_member'),
        ),
        migrations.AddIndex(
            model_name='projecttag',
            index=models.Index(fields=['project'], name='w_craft_bac_project_3ebb5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='projecttag',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_project_tag_name'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['project', 'status'], name='w_craft_bac_project_31d740_idx'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['project', 'order'], name='w_craft_bac_project_9b09e0_idx'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['project', 'updated_at'], name='w_craft_bac_project_23f57e_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenecharacter',
            constraint=models.UniqueConstraint(fields=('scene', 'character'), name='uniq_scene_character'),
        ),
        migrations.AddConstraint(
            model_name='scenemusic',
            constraint=models.UniqueConstraint(fields=('scene', 'track'), name='uniq_scene_music'),
        ),
    ]
