# Generated by Django 5.2.13 on 2026-05-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0024_remove_studiocharacter_draft_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='activity_type',
            field=models.CharField(choices=[('character_created', 'Персонаж создан'), ('character_updated', 'Персонаж обновлён'), ('scene_created', 'Сцена создана'), ('scene_render_completed', 'Рендер сцены завершён'), ('music_added', 'Музыка добавлена'), ('location_created', 'Локация создана'), ('asset_uploaded', 'Файл загружен'), ('project_updated', 'Проект обновлён'), ('project_status_changed', 'Статус проекта изменён'), ('project_archived', 'Проект архивирован')], max_length=40),
        ),
    ]
