# Generated by Django 5.2.13 on 2026-06-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0030_studiocharacter_model3d_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactergenerationjob',
            name='job_type',
            field=models.CharField(choices=[('initial_variants', 'Initial variants'), ('edit_variants', 'Edit variants'), ('outfit_variants', 'Outfit variants'), ('expression_variants', 'Expression variants'), ('character_sheet', 'Character sheet'), ('reference_extraction', 'Reference extraction'), ('reference_variants', 'Reference-based variants')], max_length=64),
        ),
    ]
