# Generated by Django 5.2.13 on 2026-06-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0031_alter_charactergenerationjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiocharacter',
            name='model3d_autofit_done',
            field=models.BooleanField(default=False),
        ),
    ]
