# Generated by Django 5.2.13 on 2026-06-13 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0032_studiocharacter_model3d_autofit_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_music_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_music_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='target_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='target_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='custom_team_role',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='team_role',
            field=models.CharField(blank=True, choices=[('producer', 'Продюсер'), ('director', 'Режиссёр'), ('screenwriter', 'Сценарист'), ('character_artist', 'Художник персонажей'), ('environment_artist', 'Художник окружения'), ('cinematographer', 'Оператор'), ('editor', 'Монтажёр'), ('sound_designer', 'Звукорежиссёр'), ('other', 'Другое')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='camera_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scene',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scene',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scene',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='activity_type',
            field=models.CharField(choices=[('character_created', 'Персонаж создан'), ('character_updated', 'Персонаж обновлён'), ('scene_created', 'Сцена создана'), ('scene_render_completed', 'Рендер сцены завершён'), ('music_added', 'Музыка добавлена'), ('location_created', 'Локация создана'), ('asset_uploaded', 'Файл загружен'), ('project_updated', 'Проект обновлён'), ('project_status_changed', 'Статус проекта изменён'), ('project_archived', 'Проект архивирован'), ('member_invited', 'Участник приглашён'), ('invitation_accepted', 'Приглашение принято'), ('invitation_declined', 'Приглашение отклонено'), ('invitation_cancelled', 'Приглашение отменено'), ('member_role_changed', 'Роль изменена'), ('member_removed', 'Участник удалён'), ('member_left', 'Участник покинул проект'), ('ownership_transferred', 'Владение передано')], max_length=40),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('editor', 'Редактор'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('access_role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('editor', 'Редактор'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20)),
                ('team_role', models.CharField(blank=True, choices=[('producer', 'Продюсер'), ('director', 'Режиссёр'), ('screenwriter', 'Сценарист'), ('character_artist', 'Художник персонажей'), ('environment_artist', 'Художник окружения'), ('cinematographer', 'Оператор'), ('editor', 'Монтажёр'), ('sound_designer', 'Звукорежиссёр'), ('other', 'Другое')], default='', max_length=32)),
                ('custom_team_role', models.CharField(blank=True, default='', max_length=64)),
                ('invitation_type', models.CharField(choices=[('username', 'По username'), ('link', 'По ссылке')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_project_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_project_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_project_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='w_craft_back.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'status'], name='w_craft_bac_project_a5e7d3_idx'), models.Index(fields=['invited_user', 'status'], name='w_craft_bac_invited_ed5dc0_idx'), models.Index(fields=['status', 'expires_at'], name='w_craft_bac_status_ccc3ef_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('invited_user__isnull', False), ('status', 'pending')), fields=('project', 'invited_user'), name='uniq_pending_username_invitation')],
            },
        ),
    ]
