# Generated by Django 5.2.13 on 2026-07-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0034_backfill_owner_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiocharacter',
            name='model3d_autofit_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
