# Generated by Django 5.2.13 on 2026-07-26 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reindex_poster_variants(apps, schema_editor):
    """Normalize historical duplicate indexes without deleting poster files."""
    variant_model = apps.get_model('w_craft_back', 'PosterVariant')
    if schema_editor.connection.vendor == 'postgresql':
        table_name = schema_editor.quote_name(variant_model._meta.db_table)
        schema_editor.execute(
            f'LOCK TABLE {table_name} IN SHARE ROW EXCLUSIVE MODE'
        )

    job_ids = (
        variant_model.objects.order_by()
        .values_list('job_id', flat=True)
        .distinct()
        .iterator(chunk_size=1000)
    )
    for job_id in job_ids:
        variants = list(
            variant_model.objects.filter(job_id=job_id).order_by(
                'variant_index',
                'created_at',
                'id',
            )
        )
        if len(variants) > 32768:
            raise RuntimeError(
                f'Poster job {job_id} has too many variants to reindex safely'
            )
        changed = []
        for variant_index, variant in enumerate(variants):
            if variant.variant_index != variant_index:
                variant.variant_index = variant_index
                changed.append(variant)
        if changed:
            variant_model.objects.bulk_update(
                changed,
                ['variant_index'],
                batch_size=1000,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0037_scene_script_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterProviderCircuit',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('provider_key', models.CharField(max_length=255, unique=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('opened_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='postergenerationjob',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),

        migrations.AddField(
            model_name='postergenerationjob',
            name='operation',
            field=models.CharField(
                choices=[('generate', 'Генерация'), ('edit', 'Редактирование')],
                default='generate',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='postergenerationjob',
            name='request_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='postergenerationjob',
            name='source_variant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='edit_jobs',
                to='w_craft_back.postervariant',
            ),
        ),
        migrations.RunPython(
            reindex_poster_variants,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='postergenerationjob',
            constraint=models.UniqueConstraint(
                condition=models.Q(('idempotency_key', ''), _negated=True),
                fields=('project', 'user', 'operation', 'idempotency_key'),
                name='uniq_poster_job_idempotency_key',
            ),
        ),
        migrations.AddConstraint(
            model_name='postervariant',
            constraint=models.UniqueConstraint(
                fields=('job', 'variant_index'),
                name='uniq_poster_job_variant_index',
            ),
        ),
    ]
