# Generated by Django 5.2.13 on 2026-07-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0038_posterprovidercircuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postergenerationjob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
