# Generated by Django 5.2.13 on 2026-07-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0039_postergenerationjob_lease_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postergenerationjob',
            name='error_http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
