# Generated by Django 5.2.13 on 2026-07-26 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def resequence_scenes(apps, schema_editor):
    Scene = apps.get_model("w_craft_back", "Scene")
    db_alias = schema_editor.connection.alias
    current_project_id = None
    next_order = 0
    scenes = (
        Scene.objects.using(db_alias)
        .order_by("project_id", "order", "created_at", "pk")
    )
    for scene in scenes.iterator():
        if scene.project_id != current_project_id:
            current_project_id = scene.project_id
            next_order = 1
        else:
            next_order += 1
        if scene.order != next_order:
            Scene.objects.using(db_alias).filter(pk=scene.pk).update(order=next_order)


def deduplicate_graph_edges(apps, schema_editor):
    GraphEdge = apps.get_model("w_craft_back", "GraphEdge")
    db_alias = schema_editor.connection.alias
    duplicate_groups = (
        GraphEdge.objects.using(db_alias)
        .values("project_id", "from_node", "to_node", "label_id")
        .annotate(
            keep_id=models.Min("pk"),
            edge_count=models.Count("pk"),
        )
        .filter(edge_count__gt=1)
    )
    for group in duplicate_groups.iterator():
        GraphEdge.objects.using(db_alias).filter(
            project_id=group["project_id"],
            from_node=group["from_node"],
            to_node=group["to_node"],
            label_id=group["label_id"],
        ).exclude(pk=group["keep_id"]).delete()

    conflicting_direction = (
        GraphEdge.objects.using(db_alias)
        .values("project_id", "from_node", "to_node")
        .annotate(label_count=models.Count("label_id", distinct=True))
        .filter(label_count__gt=1)
        .order_by("project_id", "from_node", "to_node")
        .first()
    )
    if conflicting_direction:
        raise RuntimeError(
            "Conflicting graph edge labels require manual repair before migration "
            f"for project_id={conflicting_direction['project_id']}, "
            f"direction={conflicting_direction['from_node']!r}->"
            f"{conflicting_direction['to_node']!r}."
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0042_userkey_authentication_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterasset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_assets', to='w_craft_back.userkey'),
        ),
        migrations.AlterField(
            model_name='charactergenerationjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_generation_jobs', to='w_craft_back.userkey'),
        ),
        migrations.AlterField(
            model_name='characterrevision',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_revisions', to='w_craft_back.userkey'),
        ),
        migrations.AlterField(
            model_name='graphedge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_craft_back.userkey'),
        ),
        migrations.RunPython(deduplicate_graph_edges, noop_reverse),
        migrations.RemoveConstraint(
            model_name='graphedge',
            name='uniq_graph_edge_direction',
        ),
        migrations.AddConstraint(
            model_name='graphedge',
            constraint=models.UniqueConstraint(fields=('project', 'from_node', 'to_node'), name='uniq_graph_edge_direction'),
        ),
        migrations.AlterField(
            model_name='menufolder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_craft_back.userkey'),
        ),
        migrations.AlterField(
            model_name='postergenerationjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster_generation_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postervariant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectgenerationjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_generation_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectposter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_posters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scene',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studiocharacter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_characters', to='w_craft_back.userkey'),
        ),
        migrations.RunPython(resequence_scenes, noop_reverse),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 1)), name='chk_scene_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='uniq_scene_order_per_project'),
        ),
    ]
