# Generated by Django 5.2.13 on 2026-08-02 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_music_tracks(apps, schema_editor):
    """Create metadata-only assets/versions without opening media storage."""

    del schema_editor
    MusicTrack = apps.get_model("w_craft_back", "MusicTrack")
    MusicAsset = apps.get_model("w_craft_back", "MusicAsset")
    MusicTrackVersion = apps.get_model("w_craft_back", "MusicTrackVersion")
    SceneMusic = apps.get_model("w_craft_back", "SceneMusic")
    active_versions = {}
    tracks = (
        MusicTrack.objects.filter(audio_file__isnull=False)
        .exclude(audio_file="")
        .iterator(chunk_size=500)
    )
    for track in tracks:
        asset = MusicAsset.objects.create(
            project_id=track.project_id,
            file=str(track.audio_file),
            asset_role="generated",
            origin="legacy",
            duration_seconds=(
                track.duration_seconds if track.duration_seconds > 0 else None
            ),
            verification_status="legacy_unverified",
            moderation_status="not_required",
            created_by_id=track.created_by_id,
        )
        version = MusicTrackVersion.objects.create(
            track_id=track.pk,
            version_number=1,
            asset_id=asset.pk,
            created_by_id=track.created_by_id,
        )
        active_versions[track.pk] = version.pk
        MusicTrack.objects.filter(pk=track.pk).update(
            active_version_id=version.pk,
            source="legacy",
        )
    for track_id, version_id in active_versions.items():
        SceneMusic.objects.filter(track_id=track_id).update(
            track_version_id=version_id
        )


def reverse_legacy_music_backfill(apps, schema_editor):
    """Detach additive pointers; legacy audio_file remains untouched."""

    del schema_editor
    MusicTrack = apps.get_model("w_craft_back", "MusicTrack")
    SceneMusic = apps.get_model("w_craft_back", "SceneMusic")
    SceneMusic.objects.update(track_version_id=None)
    MusicTrack.objects.filter(source="legacy").update(
        active_version_id=None,
        source="manual",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0048_remove_unused_project_generation_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated'), ('legacy', 'Legacy')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='MusicAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to='projects/music/assets/')),
                ('asset_role', models.CharField(choices=[('generated', 'Generated audio'), ('reference', 'Private audio reference')], max_length=16)),
                ('origin', models.CharField(choices=[('generated', 'Generated'), ('upload', 'Uploaded'), ('legacy', 'Legacy track')], max_length=16)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('legacy_unverified', 'Legacy unverified'), ('missing', 'Missing')], default='verified', max_length=24)),
                ('moderation_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_required', max_length=16)),
                ('rights_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rights_statement_version', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=255)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('waveform_peaks', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_music_assets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_assets', to='w_craft_back.project')),
                ('rights_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_music_reference_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief', models.JSONField(default=dict)),
                ('compiled_request', models.JSONField(default=dict)),
                ('provider', models.CharField(default='mock', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('cancellation_requested', 'Cancellation requested'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('preparing_reference', 'Preparing reference'), ('generating', 'Generating'), ('polling', 'Polling provider'), ('validating', 'Validating output'), ('storing', 'Storing output'), ('finalized', 'Finalized'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('variant_count', models.PositiveSmallIntegerField(default=2)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('provider_started_at', models.DateTimeField(blank=True, null=True)),
                ('provider_job_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_reference_id', models.CharField(blank=True, default='', max_length=255)),
                ('next_poll_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('error_detail', models.CharField(blank=True, default='', max_length=500)),
                ('error_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_retryable', models.BooleanField(blank=True, null=True)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='music_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_generation_jobs', to='w_craft_back.project')),
                ('reference_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='w_craft_back.musicasset')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='w_craft_back.musicgenerationjob')),
                ('target_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='w_craft_back.musictrack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicTrackVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('brief_snapshot', models.JSONField(blank=True, default=dict)),
                ('lyrics_snapshot', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_versions', to='w_craft_back.musicasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_music_track_versions', to=settings.AUTH_USER_MODEL)),
                ('reference_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_track_versions', to='w_craft_back.musicasset')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='w_craft_back.musictrack')),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.AddField(
            model_name='musictrack',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_tracks', to='w_craft_back.musictrackversion'),
        ),
        migrations.AddField(
            model_name='scenemusic',
            name='track_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scene_usages', to='w_craft_back.musictrackversion'),
        ),
        migrations.CreateModel(
            name='MusicVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_index', models.PositiveSmallIntegerField()),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('failed', 'Failed')], default='generated', max_length=16)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_variant', to='w_craft_back.musicasset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='w_craft_back.musicgenerationjob')),
            ],
            options={
                'ordering': ['variant_index'],
            },
        ),
        migrations.AddField(
            model_name='musictrackversion',
            name='source_variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_version', to='w_craft_back.musicvariant'),
        ),
        migrations.AddIndex(
            model_name='musicasset',
            index=models.Index(fields=['project', 'asset_role', '-created_at'], name='w_craft_bac_project_6ce90d_idx'),
        ),
        migrations.AddIndex(
            model_name='musicasset',
            index=models.Index(fields=['verification_status'], name='w_craft_bac_verific_608d0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='musicasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'verified'), _negated=True), models.Q(models.Q(('mime_type', ''), _negated=True), ('size_bytes__gt', 0), models.Q(('checksum_sha256', ''), _negated=True), ('duration_seconds__gt', 0)), _connector='OR'), name='chk_music_asset_verified_metadata'),
        ),
        migrations.AddConstraint(
            model_name='musicasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset_role', 'reference'), _negated=True), models.Q(('origin', 'upload'), ('rights_confirmed_by__isnull', False), ('rights_confirmed_at__isnull', False), models.Q(('rights_statement_version', ''), _negated=True)), _connector='OR'), name='chk_music_reference_attestation'),
        ),
        migrations.AddIndex(
            model_name='musicgenerationjob',
            index=models.Index(fields=['project', '-created_at'], name='w_craft_bac_project_e7b9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='musicgenerationjob',
            index=models.Index(fields=['actor', 'status'], name='w_craft_bac_actor_i_ae94b3_idx'),
        ),
        migrations.AddIndex(
            model_name='musicgenerationjob',
            index=models.Index(fields=['status', 'created_at'], name='w_craft_bac_status_3886d4_idx'),
        ),
        migrations.AddIndex(
            model_name='musicgenerationjob',
            index=models.Index(fields=['status', 'next_poll_at'], name='w_craft_bac_status_9c72b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='musicgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(('variant_count__in', (1, 2))), name='chk_music_job_variant_count'),
        ),
        migrations.AddConstraint(
            model_name='musicgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='chk_music_job_attempts'),
        ),
        migrations.AddConstraint(
            model_name='musicgenerationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('project', 'actor', 'idempotency_key'), name='uniq_music_job_idempotency'),
        ),
        migrations.AddIndex(
            model_name='musicvariant',
            index=models.Index(fields=['job'], name='w_craft_bac_job_id_279ba7_idx'),
        ),
        migrations.AddConstraint(
            model_name='musicvariant',
            constraint=models.UniqueConstraint(fields=('job', 'variant_index'), name='uniq_music_job_variant_index'),
        ),
        migrations.AddConstraint(
            model_name='musictrackversion',
            constraint=models.UniqueConstraint(fields=('track', 'version_number'), name='uniq_music_track_version_number'),
        ),
        migrations.RunPython(
            backfill_legacy_music_tracks,
            reverse_legacy_music_backfill,
        ),
    ]
