# Generated by Django 5.2.13 on 2026-08-07 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0049_musictrack_archived_at_musictrack_source_musicasset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('location', 'Локация'), ('prop', 'Предмет'), ('wardrobe', 'Костюм'), ('vehicle', 'Транспорт'), ('symbol', 'Символ'), ('other', 'Другое')], max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('brief', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_references', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_references', to='w_craft_back.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='w_craft_back.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('generate', 'Generate'), ('edit', 'Edit')], max_length=16)),
                ('brief_snapshot', models.JSONField(default=dict)),
                ('compiled_request', models.JSONField(default=dict)),
                ('variant_count', models.PositiveSmallIntegerField(default=1)),
                ('requested_model', models.CharField(blank=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('cancellation_requested', 'Cancellation requested'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('compiling', 'Compiling'), ('generating', 'Generating'), ('validating', 'Validating'), ('storing', 'Storing'), ('finalized', 'Finalized'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('provider_started_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('error_detail', models.CharField(blank=True, default='', max_length=500)),
                ('error_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_retryable', models.BooleanField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_jobs', to='w_craft_back.project')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='w_craft_back.projectreference')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='w_craft_back.referencegenerationjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_index', models.PositiveSmallIntegerField()),
                ('seed', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('applied', 'Applied'), ('discarded', 'Discarded')], default='generated', max_length=16)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reference_variants', to='w_craft_back.projectasset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='w_craft_back.referencegenerationjob')),
                ('thumbnail_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reference_thumbnail_variants', to='w_craft_back.projectasset')),
            ],
            options={
                'ordering': ['variant_index'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('upload', 'Upload'), ('generated', 'Generated'), ('edit', 'Edit'), ('legacy', 'Legacy')], max_length=16)),
                ('brief_snapshot', models.JSONField(default=dict)),
                ('compiled_prompt', models.TextField(blank=True, default='')),
                ('negative_prompt', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('seed', models.CharField(blank=True, default='', max_length=128)),
                ('rights_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rights_statement_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reference_versions', to='w_craft_back.projectasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reference_versions', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='w_craft_back.projectreference')),
                ('rights_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_reference_versions', to=settings.AUTH_USER_MODEL)),
                ('source_variant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_version', to='w_craft_back.referencevariant')),
                ('thumbnail_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reference_thumbnail_versions', to='w_craft_back.projectasset')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='referencegenerationjob',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edit_jobs', to='w_craft_back.referenceversion'),
        ),
        migrations.AddField(
            model_name='projectreference',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_references', to='w_craft_back.referenceversion'),
        ),
        migrations.CreateModel(
            name='SceneReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(choices=[('environment', 'Environment'), ('hero_prop', 'Hero prop'), ('set_dressing', 'Set dressing'), ('wardrobe', 'Wardrobe'), ('vehicle', 'Vehicle'), ('symbol', 'Symbol'), ('other', 'Other')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scene_references', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_usages', to='w_craft_back.projectreference')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_usages', to='w_craft_back.scene')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scene_usages', to='w_craft_back.referenceversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCharacterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('owns', 'Owns'), ('wears', 'Wears'), ('carries', 'Carries'), ('uses', 'Uses'), ('important', 'Important'), ('associated', 'Associated')], max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_links', to='w_craft_back.studiocharacter')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='w_craft_back.projectreference')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reference', 'character', 'relation'), name='uniq_reference_character_relation')],
            },
        ),
        migrations.AddConstraint(
            model_name='referencevariant',
            constraint=models.UniqueConstraint(fields=('job', 'variant_index'), name='uniq_reference_job_variant'),
        ),
        migrations.AddConstraint(
            model_name='referenceversion',
            constraint=models.UniqueConstraint(fields=('reference', 'version_number'), name='uniq_reference_version_number'),
        ),
        migrations.AddIndex(
            model_name='referencegenerationjob',
            index=models.Index(fields=['project', '-created_at'], name='w_craft_bac_project_fb32bb_idx'),
        ),
        migrations.AddIndex(
            model_name='referencegenerationjob',
            index=models.Index(fields=['reference', 'status'], name='w_craft_bac_referen_1be7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='referencegenerationjob',
            index=models.Index(fields=['status', 'created_at'], name='w_craft_bac_status_bb7cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='referencegenerationjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='w_craft_bac_status_cf9d61_idx'),
        ),
        migrations.AddConstraint(
            model_name='referencegenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(('variant_count__in', (1, 2, 4))), name='chk_reference_job_variant_count'),
        ),
        migrations.AddConstraint(
            model_name='referencegenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='chk_reference_job_attempts'),
        ),
        migrations.AddConstraint(
            model_name='referencegenerationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('project', 'actor', 'idempotency_key'), name='uniq_reference_job_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='referencegenerationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'processing', 'cancellation_requested'))), fields=('reference',), name='uniq_reference_active_job'),
        ),
        migrations.AddIndex(
            model_name='projectreference',
            index=models.Index(fields=['project', 'archived_at', '-updated_at'], name='w_craft_bac_project_dfdd0d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectreference',
            index=models.Index(fields=['project', 'category', 'archived_at'], name='w_craft_bac_project_0ae2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectreference',
            index=models.Index(fields=['location'], name='w_craft_bac_locatio_1cb01d_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenereference',
            constraint=models.UniqueConstraint(fields=('scene', 'reference'), name='uniq_scene_reference'),
        ),
    ]
