# Generated by Django 5.2.13 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("w_craft_back", "0050_reference_library"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE character_generation_jobs
                            ADD COLUMN IF NOT EXISTS provider_snapshot
                            jsonb NOT NULL DEFAULT '{}'::jsonb;
                        ALTER TABLE character_generation_jobs
                            ALTER COLUMN provider TYPE varchar(255),
                            ALTER COLUMN model_name TYPE varchar(255),
                            ALTER COLUMN model_version TYPE varchar(255);
                        ALTER TABLE user_profiles
                            ALTER COLUMN image_generation_model TYPE varchar(255);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="charactergenerationjob",
                    name="provider_snapshot",
                    field=models.JSONField(blank=True, default=dict),
                ),
                migrations.AlterField(
                    model_name="charactergenerationjob",
                    name="model_name",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AlterField(
                    model_name="charactergenerationjob",
                    name="model_version",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AlterField(
                    model_name="charactergenerationjob",
                    name="provider",
                    field=models.CharField(blank=True, default="mock", max_length=255),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="image_generation_model",
                    field=models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "Image model registry or catalog key, e.g. "
                            '"gemini-imagen-4". Empty falls back to '
                            "env/registry default."
                        ),
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
