# Generated by Django 5.2.13 on 2026-08-14 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0054_normalize_runtime_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_accounts',
            },
        ),
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('demo_top_up', 'Demo top-up'), ('transfer_out', 'Transfer sent'), ('transfer_in', 'Transfer received'), ('reserve', 'Credits reserved'), ('capture', 'Reserved credits charged'), ('release', 'Reserved credits released'), ('refund', 'Credits refunded'), ('adjustment', 'Administrative adjustment')], max_length=32)),
                ('available_delta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reserved_delta', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('available_balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reserved_balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='w_craft_back.creditaccount')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledger_counterparties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_ledger_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='creditaccount',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0)), name='credit_account_available_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='creditaccount',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance__gte', 0)), name='credit_account_reserved_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='credit_ledger_acct_created'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['account', 'operation_type', 'created_at'], name='credit_ledger_type_created'),
        ),
        migrations.AddConstraint(
            model_name='creditledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('account', 'idempotency_key'), name='credit_ledger_account_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='creditledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('available_delta', 0), ('reserved_delta', 0), _negated=True), name='credit_ledger_nonzero_delta'),
        ),
        migrations.AddConstraint(
            model_name='creditledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance_after__gte', 0)), name='credit_ledger_available_after_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='creditledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance_after__gte', 0)), name='credit_ledger_reserved_after_nonnegative'),
        ),
    ]
