# Generated by Django 5.2.13 on 2026-08-14 18:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0055_credits_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditaccount',
            name='available_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='reserved_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='creditledgerentry',
            name='available_balance_after',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='creditledgerentry',
            name='available_delta',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='creditledgerentry',
            name='reserved_balance_after',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='creditledgerentry',
            name='reserved_delta',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='GenerationCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=32)),
                ('job_id', models.CharField(max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=128)),
                ('model_name', models.CharField(blank=True, default='', max_length=300)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('estimated_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('reserved_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('charged_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('uncovered_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('cost_is_estimate', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('captured', 'Captured'), ('released', 'Released')], default='reserved', max_length=16)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('provider_usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_charges', to='w_craft_back.creditaccount')),
            ],
            options={
                'db_table': 'generation_charges',
                'indexes': [models.Index(fields=['account', 'created_at'], name='generation_charge_acct_created')],
                'constraints': [models.UniqueConstraint(fields=('domain', 'job_id'), name='generation_charge_job_unique'), models.CheckConstraint(condition=models.Q(('estimated_cost__gte', 0), ('reserved_amount__gte', 0), ('charged_amount__gte', 0), ('uncovered_cost__gte', 0)), name='generation_charge_amounts_nonnegative')],
            },
        ),
    ]
