# Generated by Django 5.2.13 on 2026-08-14 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0056_alter_creditaccount_available_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAdminAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('adjustment', 'Balance adjustment'), ('refund', 'Manual refund'), ('freeze', 'Wallet frozen'), ('unfreeze', 'Wallet unfrozen')], max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'credit_admin_audit_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='freeze_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='frozen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_credit_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='is_frozen',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='generationcharge',
            name='operation',
            field=models.CharField(default='generate', max_length=32),
        ),
        migrations.AddField(
            model_name='generationcharge',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_charges', to='w_craft_back.project'),
        ),
        migrations.AddField(
            model_name='generationcharge',
            name='routing_mode',
            field=models.CharField(default='manual', max_length=16),
        ),
        migrations.AddIndex(
            model_name='generationcharge',
            index=models.Index(fields=['account', 'settled_at'], name='generation_charge_acct_settled'),
        ),
        migrations.AddIndex(
            model_name='generationcharge',
            index=models.Index(fields=['project', 'settled_at'], name='generation_charge_proj_settled'),
        ),
        migrations.AddField(
            model_name='creditadminauditevent',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_audit_events', to='w_craft_back.creditaccount'),
        ),
        migrations.AddField(
            model_name='creditadminauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_admin_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='creditadminauditevent',
            index=models.Index(fields=['account', 'created_at'], name='credit_admin_acct_created'),
        ),
        migrations.AddConstraint(
            model_name='creditadminauditevent',
            constraint=models.UniqueConstraint(fields=('account', 'idempotency_key'), name='credit_admin_audit_account_idem_unique'),
        ),
    ]
