# Generated by Django 5.2.13 on 2026-08-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0057_credit_routing_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='postergenerationjob',
            name='provider_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='referencegenerationjob',
            name='provider_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
