# Generated by Django 5.2.13 on 2026-08-15 09:44

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("w_craft_back", "0058_generation_route_snapshots"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="credit_budget_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="creditadminauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("adjustment", "Balance adjustment"),
                    ("refund", "Manual refund"),
                    ("freeze", "Wallet frozen"),
                    ("unfreeze", "Wallet unfrozen"),
                    ("transfer", "Administrative transfer"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("credit_budget_limit__isnull", True),
                    ("credit_budget_limit__gte", 0),
                    _connector="OR",
                ),
                name="project_credit_budget_nonnegative",
            ),
        ),
    ]
