# Generated by Django 5.2.13 on 2026-08-20 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0060_musicgenerationjob_provider_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sound_effects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_effects', to='w_craft_back.project')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SoundEffectAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to='projects/sound-effects/assets/')),
                ('mime_type', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('duration_seconds', models.DecimalField(decimal_places=3, max_digits=8)),
                ('provider', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=128)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=255)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sound_effect_assets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_effect_assets', to='w_craft_back.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoundEffectGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request', models.JSONField(default=dict)),
                ('provider', models.CharField(default='elevenlabs-sfx', max_length=64)),
                ('model_name', models.CharField(default='eleven_text_to_sound_v2', max_length=128)),
                ('provider_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('storing', 'Storing'), ('finalized', 'Finalized'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('provider_started_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('error_detail', models.CharField(blank=True, default='', max_length=500)),
                ('error_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_retryable', models.BooleanField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sound_effect_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_effect_generation_jobs', to='w_craft_back.project')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='w_craft_back.soundeffectgenerationjob')),
                ('target_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='w_craft_back.soundeffect')),
                ('target_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sound_effect_generation_jobs', to='w_craft_back.scene')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoundEffectVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_variant', to='w_craft_back.soundeffectasset')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='w_craft_back.soundeffectgenerationjob')),
            ],
        ),
        migrations.CreateModel(
            name='SoundEffectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('request_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effect_versions', to='w_craft_back.soundeffectasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sound_effect_versions', to=settings.AUTH_USER_MODEL)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='w_craft_back.soundeffect')),
                ('source_variant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_version', to='w_craft_back.soundeffectvariant')),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.AddField(
            model_name='soundeffect',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_effects', to='w_craft_back.soundeffectversion'),
        ),
        migrations.CreateModel(
            name='SceneSoundEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_seconds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_effect_assignments', to='w_craft_back.scene')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_assignments', to='w_craft_back.soundeffect')),
                ('effect_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scene_assignments', to='w_craft_back.soundeffectversion')),
            ],
            options={
                'ordering': ['scene_id', 'start_time_seconds', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='soundeffectasset',
            index=models.Index(fields=['project', '-created_at'], name='w_craft_bac_project_a700ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='soundeffectasset',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='chk_sfx_asset_positive_size'),
        ),
        migrations.AddConstraint(
            model_name='soundeffectasset',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gt', 0)), name='chk_sfx_asset_positive_duration'),
        ),
        migrations.AddIndex(
            model_name='soundeffectgenerationjob',
            index=models.Index(fields=['project', '-created_at'], name='w_craft_bac_project_95413f_idx'),
        ),
        migrations.AddIndex(
            model_name='soundeffectgenerationjob',
            index=models.Index(fields=['status', 'created_at'], name='w_craft_bac_status_0d70c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='soundeffectgenerationjob',
            constraint=models.UniqueConstraint(fields=('project', 'actor', 'idempotency_key'), name='uniq_sfx_job_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='soundeffectgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='chk_sfx_job_attempts'),
        ),
        migrations.AddConstraint(
            model_name='soundeffectversion',
            constraint=models.UniqueConstraint(fields=('effect', 'version_number'), name='uniq_sfx_effect_version_number'),
        ),
        migrations.AddIndex(
            model_name='soundeffect',
            index=models.Index(fields=['project', 'archived_at'], name='w_craft_bac_project_340d9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenesoundeffect',
            constraint=models.UniqueConstraint(fields=('scene', 'effect', 'start_time_seconds'), name='uniq_scene_sfx_position'),
        ),
        migrations.AddConstraint(
            model_name='scenesoundeffect',
            constraint=models.CheckConstraint(condition=models.Q(('start_time_seconds__gte', 0)), name='chk_scene_sfx_nonnegative_start'),
        ),
    ]
