# Generated by Django 5.2.13 on 2026-08-20 18:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0061_sound_effects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneStoryboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_scene_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('confirmed_scene_version', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scene_storyboards', to='w_craft_back.projectasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scene_storyboards', to=settings.AUTH_USER_MODEL)),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storyboard', to='w_craft_back.scene')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scene_storyboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['source_scene_version'], name='w_craft_bac_source__a3a8d0_idx'), models.Index(fields=['confirmed_scene_version'], name='w_craft_bac_confirm_a26384_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_video_shots', to=settings.AUTH_USER_MODEL)),
                ('final_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='final_for_video_shots', to='w_craft_back.projectasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_shots', to='w_craft_back.project')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_shots', to='w_craft_back.scene')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_video_shots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scene__order', 'order', 'created_at'],
                'indexes': [models.Index(fields=['project', 'scene', 'order'], name='w_craft_bac_project_c2db00_idx'), models.Index(fields=['project', 'final_asset'], name='w_craft_bac_project_f9381d_idx')],
                'constraints': [models.UniqueConstraint(fields=('scene', 'order'), name='uniq_video_shot_order_per_scene')],
            },
        ),
    ]
