# Generated by Django 5.2.13 on 2026-08-25 18:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def remove_assetless_storyboards(apps, schema_editor):
    """Remove structured-only aggregates before restoring legacy NOT NULL."""

    SceneStoryboard = apps.get_model('w_craft_back', 'SceneStoryboard')
    SceneStoryboard.objects.filter(asset_id__isnull=True).delete()


def settle_storyboard_charges_before_rollback(apps, schema_editor):
    """Settle reservations while the Storyboard generation table exists."""

    alias = schema_editor.connection.alias
    Generation = apps.get_model(
        'w_craft_back',
        'StoryboardKeyframeGeneration',
    )
    GenerationCharge = apps.get_model('w_craft_back', 'GenerationCharge')
    CreditAccount = apps.get_model('w_craft_back', 'CreditAccount')
    CreditLedgerEntry = apps.get_model('w_craft_back', 'CreditLedgerEntry')
    jobs = {
        str(job.pk): job
        for job in Generation.objects.using(alias).all()
    }
    charges = (
        GenerationCharge.objects.using(alias)
        .select_for_update()
        .filter(domain='storyboard', status='reserved')
        .order_by('pk')
    )
    for charge in charges:
        account = CreditAccount.objects.using(alias).select_for_update().get(
            pk=charge.account_id,
        )
        amount = charge.reserved_amount
        job = jobs.get(charge.job_id)
        capture_unknown = bool(
            job is not None
            and (
                job.provider_result_received_at is not None
                or (
                    job.status == 'generating'
                    and job.provider_started_at is not None
                )
            )
        )
        account.reserved_balance -= amount
        if capture_unknown:
            available_delta = Decimal('0')
            operation_type = 'capture'
            charge.actual_cost = amount
            charge.charged_amount = amount
            charge.uncovered_cost = Decimal('0')
            charge.cost_is_estimate = True
            charge.provider_usage = {
                'costSource': 'rollback-reserved-estimate',
                'outcome': 'unknown',
            }
            charge.status = 'captured'
        else:
            account.available_balance += amount
            available_delta = amount
            operation_type = 'release'
            charge.status = 'released'
        account.save(
            using=alias,
            update_fields=[
                'available_balance',
                'reserved_balance',
                'updated_at',
            ],
        )
        if amount:
            CreditLedgerEntry.objects.using(alias).create(
                account_id=account.pk,
                operation_type=operation_type,
                available_delta=available_delta,
                reserved_delta=-amount,
                available_balance_after=account.available_balance,
                reserved_balance_after=account.reserved_balance,
                correlation_id=charge.pk,
                idempotency_key=f'generation:{charge.pk}:rollback',
                description='Storyboard rollback settlement',
                metadata={
                    'generationChargeId': str(charge.pk),
                    'domain': 'storyboard',
                    'jobId': charge.job_id,
                    'rollback': True,
                },
            )
        charge.settled_at = timezone.now()
        charge.save(using=alias)


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0062_project_progress_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryboardKeyframe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('start', 'Start'), ('intermediate', 'Intermediate'), ('end', 'End')], max_length=16)),
                ('position', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='scenestoryboard',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='scene_storyboards', to='w_craft_back.projectasset'),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            remove_assetless_storyboards,
        ),
        migrations.CreateModel(
            name='StoryboardKeyframeGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('request_snapshot', models.JSONField(default=dict)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('requested_model', models.CharField(blank=True, default='', max_length=128)),
                ('provider_snapshot', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('selected_provider', models.CharField(blank=True, default='', max_length=64)),
                ('selected_model', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('provider_started_at', models.DateTimeField(blank=True, null=True)),
                ('provider_result_received_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('error_detail', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storyboard_keyframe_generations', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='storyboard_keyframe_generations', to='w_craft_back.projectasset')),
                ('keyframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='w_craft_back.storyboardkeyframe')),
            ],
            options={
                'ordering': ['-revision', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='storyboardkeyframe',
            name='current_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='w_craft_back.storyboardkeyframegeneration'),
        ),
        migrations.CreateModel(
            name='StoryboardShot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_storyboard_shots', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storyboard_shots', to='w_craft_back.location')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='w_craft_back.scenestoryboard')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_storyboard_shots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='storyboardkeyframe',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyframes', to='w_craft_back.storyboardshot'),
        ),
        migrations.CreateModel(
            name='CameraTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_movement', models.CharField(choices=[('static', 'Static'), ('dolly_in', 'Dolly in'), ('dolly_out', 'Dolly out'), ('pan_left', 'Pan left'), ('pan_right', 'Pan right'), ('tilt_up', 'Tilt up'), ('tilt_down', 'Tilt down'), ('orbit_left', 'Orbit left'), ('orbit_right', 'Orbit right'), ('truck_left', 'Truck left'), ('truck_right', 'Truck right'), ('crane_up', 'Crane up'), ('crane_down', 'Crane down'), ('follow', 'Follow'), ('custom', 'Custom')], default='static', max_length=16)),
                ('override_movement', models.CharField(blank=True, choices=[('static', 'Static'), ('dolly_in', 'Dolly in'), ('dolly_out', 'Dolly out'), ('pan_left', 'Pan left'), ('pan_right', 'Pan right'), ('tilt_up', 'Tilt up'), ('tilt_down', 'Tilt down'), ('orbit_left', 'Orbit left'), ('orbit_right', 'Orbit right'), ('truck_left', 'Truck left'), ('truck_right', 'Truck right'), ('crane_up', 'Crane up'), ('crane_down', 'Crane down'), ('follow', 'Follow'), ('custom', 'Custom')], max_length=16, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_keyframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='w_craft_back.storyboardkeyframe')),
                ('to_keyframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='w_craft_back.storyboardkeyframe')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='w_craft_back.storyboardshot')),
            ],
            options={
                'ordering': ['from_keyframe__position', 'to_keyframe__position'],
            },
        ),
        migrations.CreateModel(
            name='StoryboardShotCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storyboard_shot_links', to='w_craft_back.studiocharacter')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='w_craft_back.storyboardshot')),
            ],
        ),
        migrations.AddField(
            model_name='storyboardshot',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='storyboard_shots', through='w_craft_back.StoryboardShotCharacter', to='w_craft_back.studiocharacter'),
        ),
        migrations.CreateModel(
            name='StoryboardShotReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('location', 'Location'), ('object', 'Object'), ('clothing', 'Clothing'), ('transport', 'Transport'), ('other', 'Other')], max_length=16)),
                ('title_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storyboard_shot_links', to='w_craft_back.projectreference')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_references', to='w_craft_back.storyboardshot')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyframeGenerationReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_type', models.CharField(choices=[('character', 'Character'), ('location', 'Location'), ('object', 'Object'), ('clothing', 'Clothing'), ('previous_keyframe', 'Previous keyframe'), ('previous_shot', 'Previous shot'), ('other_storyboard_keyframe', 'Other storyboard keyframe')], max_length=32)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('label_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storyboard_generation_references', to='w_craft_back.studiocharacter')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storyboard_generation_references', to='w_craft_back.location')),
                ('visual_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storyboard_generation_references', to='w_craft_back.projectreference')),
                ('keyframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_references', to='w_craft_back.storyboardkeyframe')),
                ('source_keyframe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_generation_reference', to='w_craft_back.storyboardkeyframe')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['keyframe', 'priority'], name='w_craft_bac_keyfram_df8987_idx'), models.Index(fields=['source_keyframe'], name='w_craft_bac_source__fe659a_idx'), models.Index(fields=['visual_reference'], name='w_craft_bac_visual__42345e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('keyframe',), name='uniq_storyboard_primary_reference')],
            },
        ),
        migrations.CreateModel(
            name='CameraIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.JSONField(blank=True, default=dict)),
                ('azimuth', models.CharField(choices=[('front', 'Front'), ('front_left', 'Front left'), ('left', 'Left'), ('back_left', 'Back left'), ('back', 'Back'), ('back_right', 'Back right'), ('right', 'Right'), ('front_right', 'Front right')], default='front', max_length=16)),
                ('elevation', models.CharField(choices=[('low', 'Low'), ('eye_level', 'Eye level'), ('high', 'High'), ('top', 'Top')], default='eye_level', max_length=16)),
                ('distance', models.CharField(choices=[('wide', 'Wide'), ('medium', 'Medium'), ('near', 'Near')], default='medium', max_length=16)),
                ('framing', models.CharField(choices=[('extreme_wide', 'Extreme wide'), ('wide', 'Wide'), ('full', 'Full'), ('medium', 'Medium'), ('medium_close', 'Medium close'), ('close', 'Close'), ('extreme_close', 'Extreme close'), ('ots', 'Over the shoulder'), ('pov', 'Point of view')], default='medium', max_length=20)),
                ('lens_mm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)])),
                ('composition', models.JSONField(blank=True, default=list)),
                ('camera_metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyframe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera_intent', to='w_craft_back.storyboardkeyframe')),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='w_craft_bac_updated_68f54d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('lens_mm__isnull', True), models.Q(('lens_mm__gte', 10), ('lens_mm__lte', 300)), _connector='OR'), name='chk_camera_intent_lens')],
            },
        ),
        migrations.AddIndex(
            model_name='storyboardkeyframegeneration',
            index=models.Index(fields=['keyframe', '-revision'], name='w_craft_bac_keyfram_84fe42_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboardkeyframegeneration',
            index=models.Index(fields=['status', 'created_at'], name='w_craft_bac_status_d9f81a_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboardkeyframegeneration',
            index=models.Index(fields=['status', 'lease_expires_at'], name='w_craft_bac_status_22027e_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyboardkeyframegeneration',
            constraint=models.UniqueConstraint(fields=('keyframe', 'revision'), name='uniq_storyboard_generation_revision'),
        ),
        migrations.AddConstraint(
            model_name='storyboardkeyframegeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'generating'))), fields=('keyframe',), name='uniq_storyboard_active_generation'),
        ),
        migrations.AddConstraint(
            model_name='storyboardkeyframegeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('keyframe', 'idempotency_key'), name='uniq_storyboard_generation_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='storyboardkeyframegeneration',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='chk_storyboard_generation_attempts'),
        ),
        migrations.AddIndex(
            model_name='storyboardkeyframe',
            index=models.Index(fields=['shot', 'position'], name='w_craft_bac_shot_id_7840cb_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboardkeyframe',
            index=models.Index(fields=['shot', 'type'], name='w_craft_bac_shot_id_9fd931_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyboardkeyframe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('position', Decimal('0')), ('type', 'start')), models.Q(('position', Decimal('1')), ('type', 'end')), models.Q(('position__gt', 0), ('position__lt', 1), ('type', 'intermediate')), _connector='OR'), name='chk_storyboard_keyframe_type_position'),
        ),
        migrations.AddConstraint(
            model_name='storyboardkeyframe',
            constraint=models.UniqueConstraint(fields=('shot', 'position'), name='uniq_storyboard_keyframe_position'),
        ),
        migrations.AddConstraint(
            model_name='storyboardkeyframe',
            constraint=models.UniqueConstraint(condition=models.Q(('type__in', ('start', 'end'))), fields=('shot', 'type'), name='uniq_storyboard_keyframe_boundary'),
        ),
        migrations.AddIndex(
            model_name='cameratransition',
            index=models.Index(fields=['shot', 'from_keyframe'], name='w_craft_bac_shot_id_8c256e_idx'),
        ),
        migrations.AddIndex(
            model_name='cameratransition',
            index=models.Index(fields=['shot', 'to_keyframe'], name='w_craft_bac_shot_id_5e4731_idx'),
        ),
        migrations.AddConstraint(
            model_name='cameratransition',
            constraint=models.UniqueConstraint(fields=('shot', 'from_keyframe', 'to_keyframe'), name='uniq_storyboard_camera_transition'),
        ),
        migrations.AddConstraint(
            model_name='cameratransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_keyframe', models.F('to_keyframe')), _negated=True), name='chk_storyboard_transition_distinct'),
        ),
        migrations.AddIndex(
            model_name='storyboardshotcharacter',
            index=models.Index(fields=['shot', 'character'], name='w_craft_bac_shot_id_a93281_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyboardshotcharacter',
            constraint=models.UniqueConstraint(condition=models.Q(('character__isnull', False)), fields=('shot', 'character'), name='uniq_storyboard_shot_character'),
        ),
        migrations.AddIndex(
            model_name='storyboardshot',
            index=models.Index(fields=['storyboard', 'order'], name='w_craft_bac_storybo_37c213_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboardshot',
            index=models.Index(fields=['location'], name='w_craft_bac_locatio_374088_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboardshot',
            index=models.Index(fields=['storyboard', 'updated_at'], name='w_craft_bac_storybo_066f22_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyboardshot',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='chk_storyboard_shot_order'),
        ),
        migrations.AddConstraint(
            model_name='storyboardshot',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__isnull', True), ('duration_seconds__gte', 0), _connector='OR'), name='chk_storyboard_shot_duration'),
        ),
        migrations.AddConstraint(
            model_name='storyboardshot',
            constraint=models.UniqueConstraint(fields=('storyboard', 'order'), name='uniq_storyboard_shot_order'),
        ),
        migrations.AddIndex(
            model_name='storyboardshotreference',
            index=models.Index(fields=['shot', 'role'], name='w_craft_bac_shot_id_a9543c_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboardshotreference',
            index=models.Index(fields=['reference'], name='w_craft_bac_referen_93eef3_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyboardshotreference',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__isnull', False)), fields=('shot', 'reference', 'role'), name='uniq_storyboard_shot_reference'),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            settle_storyboard_charges_before_rollback,
        ),
    ]
