# Generated by Django 5.2.13 on 2026-08-31 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0064_merge_storyboard_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneStoryboardEditorDraft',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID',
                )),
                ('payload', models.JSONField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('last_mutation_id', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='storyboard_editor_draft', to='w_craft_back.scene',
                )),
                ('updated_by', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
    ]
