# Generated by Django 5.2.13 on 2026-08-31 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0065_storyboard_editor_drafts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneStoryboardShotListJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_snapshot', models.JSONField()),
                ('expected_revision', models.PositiveIntegerField()),
                ('estimated_seconds', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('result_state', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('result', models.JSONField(null=True)),
                ('applied_revision', models.PositiveIntegerField(null=True)),
                ('apply_mutation_id', models.UUIDField(null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_expires_at', models.DateTimeField(null=True)),
                ('provider_started_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyboard_shot_list_jobs', to='w_craft_back.scene')),
            ],
        ),
        migrations.CreateModel(
            name='SceneStoryboardShotListRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('parameters', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='w_craft_back.scenestoryboardshotlistjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w_craft_back.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='scenestoryboardshotlistjob',
            index=models.Index(fields=['scene', '-created_at'], name='w_craft_bac_scene_i_be50ff_idx'),
        ),
        migrations.AddIndex(
            model_name='scenestoryboardshotlistjob',
            index=models.Index(fields=['status', 'created_at'], name='w_craft_bac_status_338e19_idx'),
        ),
        migrations.AddIndex(
            model_name='scenestoryboardshotlistjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='w_craft_bac_status_4df2b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenestoryboardshotlistjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('scene',), name='uniq_storyboard_active_shot_list'),
        ),
        migrations.AddConstraint(
            model_name='scenestoryboardshotlistrequest',
            constraint=models.UniqueConstraint(fields=('project', 'actor', 'request_id'), name='uniq_storyboard_shot_list_request'),
        ),
    ]
