# Generated by Django 5.2.13 on 2026-08-31 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_craft_back', '0066_storyboard_shot_list_jobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryboardEditorFrameJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shot_id', models.CharField(max_length=256)),
                ('keyframe_id', models.CharField(max_length=256)),
                ('request_id', models.UUIDField()),
                ('request_parameters', models.JSONField()),
                ('expected_revision', models.PositiveIntegerField()),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('request_snapshot', models.JSONField()),
                ('provider_snapshot', models.JSONField()),
                ('model', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_expires_at', models.DateTimeField(null=True)),
                ('provider_started_at', models.DateTimeField(null=True)),
                ('provider_result_received_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='storyboard_editor_frame_results', to='w_craft_back.projectasset')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyboard_editor_frame_jobs', to='w_craft_back.scene')),
            ],
        ),
        migrations.CreateModel(
            name='StoryboardEditorFrameInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='w_craft_back.characterasset')),
                ('project_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='w_craft_back.projectasset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_assets', to='w_craft_back.storyboardeditorframejob')),
            ],
        ),
        migrations.AddIndex(
            model_name='storyboardeditorframejob',
            index=models.Index(fields=['scene', '-created_at'], name='w_craft_bac_scene_i_a46999_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboardeditorframejob',
            index=models.Index(fields=['status', 'created_at'], name='w_craft_bac_status_f31d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboardeditorframejob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='w_craft_bac_status_e0985a_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyboardeditorframejob',
            constraint=models.UniqueConstraint(fields=('scene', 'actor', 'request_id'), name='uniq_editor_frame_request'),
        ),
        migrations.AddConstraint(
            model_name='storyboardeditorframejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('scene', 'keyframe_id'), name='uniq_editor_frame_active'),
        ),
    ]
