"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import datetime
import os
from pathlib import Path

# Load environment variables from backend/.env (dev convenience).
# This makes CHARACTER_STUDIO_IMAGE_PROVIDER / GEMINI_API_KEY available to Character Studio services.
try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
if load_dotenv:
    load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY is not set. Define it in backend/.env.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mptt',
    'w_craft_back.apps.WCraftBackConfig',
    'corsheaders',
    'rest_framework',
]

CORS_ORIGIN_ALLOW_ALL = os.getenv("CORS_ALLOW_ALL", "false").lower() in {"1", "true", "yes", "on"}
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000").split(",")
    if o.strip()
]
CORS_ALLOW_CREDENTIALS = True

# Browsers reject "Access-Control-Allow-Origin: *" when credentials are sent,
# so combining wildcard CORS with credentials is both insecure and broken.
if CORS_ORIGIN_ALLOW_ALL and CORS_ALLOW_CREDENTIALS and not DEBUG:
    raise RuntimeError(
        "Refusing to start: CORS_ALLOW_ALL=true is incompatible with CORS_ALLOW_CREDENTIALS=true "
        "outside DEBUG. Set explicit CORS_ALLOWED_ORIGINS instead."
    )

from corsheaders.defaults import default_headers as _cors_default_headers
CORS_ALLOW_HEADERS = (
    *_cors_default_headers,
    "x-user-token",
    "x-request-id",
    "idempotency-key",
)
CORS_EXPOSE_HEADERS = ("X-Request-ID",)


MIDDLEWARE = [
    'w_craft_back.observability.RequestContextMiddleware',
    'w_craft_back.upload_protection.UploadProtectionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'w_craft_back.api_errors.ApiErrorEnvelopeMiddleware',
]

UPLOAD_MULTIPART_OVERHEAD_BYTES = 64 * 1024
UPLOAD_DEFAULT_MULTIPART_FILE_LIMIT_BYTES = 12 * 1024 * 1024
UPLOAD_ENDPOINT_FILE_LIMITS = {
    'character-create-from-reference': 10 * 1024 * 1024,
    'character-outfit-reference-upload': 10 * 1024 * 1024,
    'character-clothing-reference-upload': 10 * 1024 * 1024,
    'character-reference-upload': 10 * 1024 * 1024,
    'project-assets': 100 * 1024 * 1024,
    'profile-me-avatar': 5 * 1024 * 1024,
    'profile-me-cover': 10 * 1024 * 1024,
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

_db_user = os.getenv('W_CRAFT_POSTGRES_USER')
_db_password = os.getenv('W_CRAFT_POSTGRES_PASSWORD')
if not _db_user or not _db_password:
    raise RuntimeError(
        "W_CRAFT_POSTGRES_USER / W_CRAFT_POSTGRES_PASSWORD are not set. Define them in backend/.env."
    )

DATABASES = {
    'default': {
        'ENGINE': os.getenv('W_CRAFT_POSTGRES_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('W_CRAFT_POSTGRES_DB', 'w_craft'),
        'USER': _db_user,
        'PASSWORD': _db_password,
        'HOST': os.getenv('W_CRAFT_POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.getenv('W_CRAFT_POSTGRES_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Logging levels are env-driven so we can turn on request-level INFO logs in
# production without a code change. Defaults preserve the previous behaviour
# (quiet by default).
_APP_LOG_LEVEL = os.getenv('CRAFT_LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO').upper()
GENERATION_LOG_RAW_PROMPTS = (
    os.getenv('GENERATION_LOG_RAW_PROMPTS', 'false').lower()
    in {'1', 'true', 'yes', 'on'}
)
_DJANGO_REQUEST_LOG_LEVEL = os.getenv('CRAFT_REQUEST_LOG_LEVEL', 'INFO' if DEBUG else 'WARNING').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'safe_django_request': {
            '()': 'w_craft_back.observability.SafeDjangoRequestFilter',
        },
    },
    'formatters': {
        'json': {
            '()': 'w_craft_back.observability.JsonLogFormatter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'w_craft_back': {
            'handlers': ['console'],
            'level': _APP_LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'filters': ['safe_django_request'],
            'level': _DJANGO_REQUEST_LOG_LEVEL,
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'filters': ['safe_django_request'],
            'level': _DJANGO_REQUEST_LOG_LEVEL,
            'propagate': False,
        },
    },
}

USER_KEY_ACCESS_TTL = datetime.timedelta(hours=1)
USER_KEY_REFRESH_TTL = datetime.timedelta(days=30)
# Temporary compatibility window for legacy JSON/form clients. The frontend
# uses X-User-Token; remove the body fallback after this UTC deadline.
USER_KEY_BODY_FALLBACK_DISABLE_AT = datetime.datetime(
    2026,
    10,
    1,
    tzinfo=datetime.timezone.utc,
)
# Includes multipart framing around the existing 10 MiB image limit.
USER_KEY_LEGACY_MULTIPART_MAX_BYTES = 12 * 1024 * 1024

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'w_craft_back.auth.authentication.UserKeyAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '600/min',
        'auth': '10/min',
        'legacy_body_auth': '120/min',
        'legacy_multipart_auth': '10/min',
    },
}

MEDIA_URL = '/media/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = Path(
    os.getenv("MEDIA_ROOT", BASE_DIR.parent / "w_craft_data" / "media")
)
SIGNED_MEDIA_BASE_URL = os.getenv("SIGNED_MEDIA_BASE_URL", "")
SIGNED_MEDIA_TTL_SECONDS = int(os.getenv("SIGNED_MEDIA_TTL_SECONDS", "300"))
MEDIA_ORPHAN_RETENTION_HOURS = int(
    os.getenv("MEDIA_ORPHAN_RETENTION_HOURS", "168")
)
MEDIA_REMOTE_FETCH_ALLOW_HTTP = (
    os.getenv("MEDIA_REMOTE_FETCH_ALLOW_HTTP", "false").lower() == "true"
)
IMAGE_PROVIDER_FETCH_TIMEOUT_SECONDS = float(
    os.getenv("IMAGE_PROVIDER_FETCH_TIMEOUT_SECONDS", "15")
)
IMAGE_PROVIDER_MAX_OUTPUT_BYTES = int(
    os.getenv("IMAGE_PROVIDER_MAX_OUTPUT_BYTES", str(20 * 1024 * 1024))
)
IMAGE_PROVIDER_MAX_OUTPUT_PIXELS = int(
    os.getenv("IMAGE_PROVIDER_MAX_OUTPUT_PIXELS", "20000000")
)
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "http://localhost:8000")
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:3000")

# Per-character 3D reconstruction. The web process stays in the lightweight
# ``backend`` environment; the detached worker invokes these tools through the
# CUDA-enabled ``basic`` conda environment.
MODEL3D_CONDA_EXE = os.getenv("MODEL3D_CONDA_EXE", os.getenv("CONDA_EXE", ""))
MODEL3D_CONDA_ENV = os.getenv("MODEL3D_CONDA_ENV", "basic")
MODEL3D_RECONSTRUCTION_PYTHON = os.getenv("MODEL3D_RECONSTRUCTION_PYTHON", "")
MODEL3D_RECONSTRUCTION_TOOLS_ROOT = os.getenv(
    "MODEL3D_RECONSTRUCTION_TOOLS_ROOT",
    str(BASE_DIR.parent / "who_craft" / "tools" / "reconstruction"),
)
MODEL3D_HUNYUAN_ROOT = os.getenv(
    "MODEL3D_HUNYUAN_ROOT",
    str(BASE_DIR.parent / "external" / "Hunyuan3D-2"),
)
MODEL3D_MODEL_ROOT = os.getenv(
    "MODEL3D_MODEL_ROOT",
    str(BASE_DIR.parent / "external" / "Hunyuan3D-2" / "models"),
)
