# INSERT INTO yourapp_genre (name, translit) VALUES
# ('Драма', 'drama'),
# ('Комедия', 'comedy'),
# ('Боевик', 'boevik'),
# ('Триллер', 'triller'),
# ('Ужасы', 'horror'),
# ('Фантастика', 'fantastika'),
# ('Приключения', 'priklyucheniya'),
# ('Мелодрама', 'melodrama'),
# ('Криминал', 'kriminal'),
# ('Вестерн', 'vestern'),
# ('Мультфильм', 'multfilm'),
# ('Документальный', 'dokumentalnyy'),
# ('Исторический', 'istoricheskiy'),
# ('Фэнтези', 'fantaziya'),
# ('Романтика', 'romantika'),
# ('Военный', 'voennyy'),
# ('Детектив', 'detektiv'),
# ('Музыкальный', 'muzykalnyy'),
# ('Спорт', 'sport'),
# ('Нуар', 'nuar'),
# ('Короткометражный', 'korotkometrazhnyy'),
# ('Экспериментальный', 'eksperimentalnyy'),
# ('Художественный', 'hudozhestvennyy'),
# ('Научно-популярный', 'nauchnopopulyarnyy'),
# ('Биография', 'biografiya'),
# ('Детский', 'detskiy'),
# ('Семейный', 'semeynyy'),
# ('Аниме', 'anime'),
# ('Игровой', 'igrovoy'),
# ('Авангардный', 'avangardnyy'),
# ('Экшн', 'ekshn'),
# ('Психологический', 'psikhologicheskiy'),
# ('Мистика', 'mistika'),
# ('Фильм-нуар', 'film-nuar'),
# ('Политический', 'politicheskiy'),
# ('Сатира', 'satira'),
# ('Трагедия', 'tragediya'),
# ('Фильм о проблемах подростков', 'film-o-problemax-podrostkov'),
# ('Черная комедия', 'chernaya-komediya'),
# ('Эпический', 'epicheskiy'),
# ('Фильм о взрослении', 'film-o-vzroslenii'),
# ('Супергеройский', 'supergeroyskiy'),
# ('Фильм о шпионаже', 'film-o-shpionazhe'),
# ('Драмеди', 'dramedi'),
# ('Фильм о путешествиях', 'film-o-puteshestviyakh'),
# ('Фильм о рекламе', 'film-o-reklame'),
# ('Фильм о религии', 'film-o-religii');



# INSERT INTO yourappname_audience (name, translit) VALUES
# ('Дети', 'children'),
# ('Подростки', 'teenagers'),
# ('Молодежь', 'youth'),
# ('Взрослые', 'adults'),
# ('Пожилые люди', 'elderly');

